sudo: required
services:
  - docker

before_install:
  - docker build -t loxosceles/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true loxosceles/react-test npm test

after_success:
  - docker build -t loxosceles/multi-client ./client
  - docker build -t loxosceles/multi-nginx ./nginx
  - docker build -t loxosceles/multi-server ./server
  - docker build -t loxosceles/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push loxosceles/multi-client
  - docker push loxosceles/multi-nginx
  - docker push loxosceles/multi-server
  - docker push loxosceles/multi-worker


